"""empty message

Revision ID: 00007b5b258b
Revises: 8d6646c40304
Create Date: 2020-07-24 22:43:09.020359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00007b5b258b'
down_revision = '8d6646c40304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('projects', 'student_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    # op.drop_constraint('projects_student_id_fkey', 'projects', type_='foreignkey')
    # op.create_foreign_key(None, 'projects', 'students', ['student_id'], ['auth_id'])
    return True
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_student_id_fkey', 'projects', 'students', ['student_id'], ['id'])
    op.alter_column('projects', 'student_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
