"""empty message

Revision ID: 03997e0e1057
Revises: 52a7321acf62
Create Date: 2020-07-24 22:10:12.647674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03997e0e1057'
down_revision = '52a7321acf62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
