"""empty message

Revision ID: 74a3a4d07e37
Revises: 00007b5b258b
Create Date: 2020-07-24 22:46:29.636494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a3a4d07e37'
down_revision = '00007b5b258b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('projects', 'student_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    # op.drop_constraint('projects_student_id_fkey', 'projects', type_='foreignkey')
    # op.create_foreign_key(None, 'projects', 'students', ['student_id'], ['auth_id'])
    # op.drop_column('students', 'id')
    return True
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_student_id_fkey', 'projects', 'students', ['student_id'], ['id'])
    op.alter_column('projects', 'student_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
