"""empty message

Revision ID: e7c7af91092c
Revises: 03997e0e1057
Create Date: 2020-07-24 22:14:31.648628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c7af91092c'
down_revision = '03997e0e1057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('projects', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('projects', 'notes')
    # ### end Alembic commands ###
