"""empty message

Revision ID: 52a7321acf62
Revises: 7741024289f2
Create Date: 2020-07-24 22:04:09.816082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a7321acf62'
down_revision = '7741024289f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_duration_in_days', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'projects', ['student_id'])
    op.drop_column('projects', 'duration_in_days')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('duration_in_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'project_duration_in_days')
    # ### end Alembic commands ###
