"""empty message

Revision ID: 8d6646c40304
Revises: ce925cd67351
Create Date: 2020-07-24 22:31:24.534088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6646c40304'
down_revision = 'ce925cd67351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('projects', 'student_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    return True
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'student_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
